package app.aaps.core.keys

enum class DoubleKey(
    override val key: Int,
    val defaultValue: Double,
    val min: Double,
    val max: Double,
    override val defaultedBySM: Boolean = false,
    val calculatedBySM: Boolean = false,
    val showInApsMode: Boolean = true,
    val showInNsClientMode: Boolean = true,
    val showInPumpControlMode: Boolean = true,
    val hideParentScreenIfHidden: Boolean = false // PreferenceScreen is final so we cannot extend and modify behavior
) : PreferenceKey {

    OverviewInsulinButtonIncrement1(R.string.key_insulin_button_increment_1, 0.5, -5.0, 5.0, defaultedBySM = true),
    OverviewInsulinButtonIncrement2(R.string.key_insulin_button_increment_2, 1.0, -5.0, 5.0, defaultedBySM = true),
    OverviewInsulinButtonIncrement3(R.string.key_insulin_button_increment_3, 2.0, -5.0, 5.0, defaultedBySM = true),
    ActionsFillButton1(R.string.key_fill_button_1, 0.3, 0.05, 20.0, defaultedBySM = true, hideParentScreenIfHidden = true),
    ActionsFillButton2(R.string.key_fill_button_2, 0.0, 0.05, 20.0, defaultedBySM = true),
    ActionsFillButton3(R.string.key_fill_button_3, 0.0, 0.05, 20.0, defaultedBySM = true),
    SafetyMaxBolus(R.string.key_safety_max_bolus, 3.0, 0.1, 25.0),
    ApsMaxBasal(R.string.key_openaps_max_basal, 1.0, 0.1, 25.0, defaultedBySM = true, calculatedBySM = true),
    ApsSmbMaxIob(R.string.key_openaps_smb_max_iob, 3.0, 0.0, 70.0, defaultedBySM = true, calculatedBySM = true),
    ApsAmaMaxIob(R.string.key_openaps_ama_max_iob, 1.5, 0.0, 25.0, defaultedBySM = true, calculatedBySM = true),
    ApsMaxDailyMultiplier(R.string.key_openaps_max_daily_safety_multiplier, 3.0, 1.0, 10.0, defaultedBySM = true),
    ApsMaxCurrentBasalMultiplier(R.string.key_openaps_current_basal_safety_multiplier, 4.0, 1.0, 10.0, defaultedBySM = true),
    ApsAmaBolusSnoozeDivisor(R.string.key_openaps_ama_bolus_snooze_dia_divisor, 2.0, 1.0, 10.0, defaultedBySM = true),
    ApsAmaMin5MinCarbsImpact(R.string.key_openaps_ama_min_5m_carbs_impact, 3.0, 1.0, 12.0, defaultedBySM = true),
    ApsSmbMin5MinCarbsImpact(R.string.key_openaps_smb_min_5m_carbs_impact, 8.0, 1.0, 12.0, defaultedBySM = true),
    AbsorptionCutOff(R.string.key_absorption_cutoff, 6.0, 4.0, 10.0),
    AbsorptionMaxTime(R.string.key_absorption_maxtime, 6.0, 4.0, 10.0),
    AutosensMin(R.string.key_openaps_autosens_min, 0.7, 0.1, 1.0, defaultedBySM = true, hideParentScreenIfHidden = true),
    AutosensMax(R.string.key_openaps_autosens_max, 1.2, 0.5, 3.0, defaultedBySM = true),
    EquilMaxBolus(R.string.key_equil_maxbolus, 10.0, 0.1, 25.0),
    OApsAIMIDynISFAdjustment(R.string.key_DynISFAdjust,85.0,1.0,500.0),
    OApsAIMIDynISFAdjustmentHyper(R.string.key_DynISFAdjusthyper,150.0,1.0,500.0),
    OApsAIMIMaxSMB(R.string.key_openapsaimi_max_smb,1.0,0.05,15.0),
    OApsAIMIweight(R.string.key_aimiweight,50.0,1.0,200.0),
    OApsAIMICHO(R.string.key_cho,50.0,1.0,150.0),
    OApsAIMITDD7(R.string.key_tdd7,40.0,1.0,150.0),
    OApsAIMIMorningFactor(R.string.key_oaps_aimi_morning_factor,50.0,1.0,150.0),
    OApsAIMIAfternoonFactor(R.string.key_oaps_aimi_afternoon_factor,50.0,1.0,150.0),
    OApsAIMIEveningFactor(R.string.key_oaps_aimi_evening_factor,50.0,1.0,150.0),
    OApsAIMIHyperFactor(R.string.key_oaps_aimi_hyper_factor,60.0,1.0,150.0),
    OApsAIMIMealPrebolus(R.string.key_prebolus_meal_mode,2.0,0.1, 10.0),
    OApsAIMIHighCarbPrebolus(R.string.key_prebolus_highcarb_mode,5.0,0.1, 10.0),
    OApsAIMIMlminutesTraining(R.string.key_nb_day_ML_training,5760.0,60.0, 20000.0, defaultedBySM = true),
    OApsAIMIMlIterationTraining(R.string.key_nb_iteration_ML_training,10000.0,100.0, 10000.0, defaultedBySM = true),
    OApsAIMIMlLearningRateTraining(R.string.key_nb_learningrate_ML_training,0.0001,0.00001, 0.1, defaultedBySM = true),
    OApsAIMIMlEpochTraining(R.string.key_nb_epoch_ML_training,200.0,10.0, 200.0, defaultedBySM = true),
    OApsAIMImealAdjISFFact(R.string.key_oaps_aimi_mealAdjFact,50.0,1.0,500.0)
}